# Generated by Django 3.0.5 on 2020-04-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200426_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_detail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_name',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
